version: "2"

networks:
  kafka-net:
    driver: bridge

services:

  producer-api:
    image: fcakiroglu16/kafka-producer-api:v1
    build:
      context: .
      dockerfile: Producer.API/Dockerfile
  consumer-api:
    image: fcakiroglu16/kafka-consumer-api:v1
    build:
      context: .
      dockerfile: Consumer.API/Dockerfile

